// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://romqubyighcxxdbpwzwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbXF1YnlpZ2hjeHhkYnB3end4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDIzMzEsImV4cCI6MjA3NDM3ODMzMX0.uPafVspi-WwlsDDUOsCLHReN36d2kYafHlmqBoKpMhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});